module.exports = {
  docsSidebar: [
    'intro',
    {
      type: 'category', label: 'ΕΡΓΑΝΗ II', items: [
        'ergani-ii/overview',
        'ergani-ii/employment-lifecycle',
        'ergani-ii/digital-organization',
        'ergani-ii/schedule',
        'ergani-ii/leave',
        'ergani-ii/overtime',
        'ergani-ii/current-state',
        'ergani-ii/monthly-employment-status',
        'ergani-ii/transition-2026',
      ],
    },
    {
      type: 'category', label: 'Ψηφιακή Κάρτα', items: [
        'digital-card/overview', 'digital-card/start-end', 'digital-card/late-submission',
        'digital-card/flexible-arrival', 'digital-card/actual-work-calendar',
        'digital-card/statuses', 'digital-card/cardscanner',
      ],
    },
    {
      type: 'category', label: 'API / XML', items: [
        'api/overview', 'api/authentication', 'api/endpoints', 'api/card-submission',
        'api/xml', 'api/documents', 'api/examples',
      ],
    },
    { type: 'category', label: 'FAQ', items: ['faq/general', 'faq/digital-card', 'faq/api'] },
    { type: 'category', label: 'Σύγκριση εκδόσεων', items: ['changes/2022-2024-2026'] },
    { type: 'category', label: 'Πλήρης πηγή 2026 — Συνοπτικός', items: [{ type: 'autogenerated', dirName: 'source-archive/2026-short' }] },
    { type: 'category', label: 'Πλήρης πηγή 2026 — Αναλυτικός', items: [{ type: 'autogenerated', dirName: 'source-archive/2026-extended' }] },
    { type: 'category', label: 'Πλήρης πηγή 2024', items: [{ type: 'autogenerated', dirName: 'source-archive/2024' }] },
    { type: 'category', label: 'Reference', items: ['reference/rules', 'reference/glossary', 'reference/sources'] },
    { type: 'category', label: 'AI Q&A', items: ['ai/overview', 'ai/implementation'] },
    'changelog',
  ],
};
